graph TD
    %% Sensors
    subgraph Input_Layer [Inputs]
        PIR[PIR Sensor]
        BTN[Button]
        ENV[Env Sensor]
        CAM[Camera Module]
        
    end


    ML[MACHINE LEARNING PROCESING]
    AI_1[AI POSE IDENTIFIER]
    AI_2[AI HEALTH STATUS]
    %% Sensors
    subgraph SECURE [Secure Layer]
        AUTH[device Authentication]
        MQTT[MQTT OVER TLS]
        THREAT[THREAT  SIMULATION]
    end

    %% Logic
    RP[RASPBERRY PI]
    EMG[Emergency]
    SF[Sensor Fusion]
    PP[Payload Parser]
    SA[Sender Azure]
    RAW[SENSORS DATA]

    %% Cloud
    subgraph Azure_Cloud [Azure Infrastructure]
        HUB[Azure IoT Hub]
        DB[(DB)]
    end

    USER[User]

    %% Connections
    PIR --> RP
    BTN --> RP
    ENV --> RP
    CAM--> RP
    RP --> ML
    ML --> AI_1
    AI_1 -->SF
    RP --> RAW
    RAW--> SF
    
    SF --> AI_2
    AI_2 -->PP
    AI_2 -->EMG
    PP --> SA
    EMG --> SA
    
    SA --> SECURE
    SECURE --> HUB

    HUB --> DB
    DB --> USER
    USER --> HUB
    EM[EMERGENCY CHANNELS]
    Azure_Cloud -->EM